# Generated by Django 5.1.6 on 2025-08-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0002_profilepicture_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='gifter',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='message',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='reveals',
        ),
        migrations.AddField(
            model_name='gift',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gift_images'),
        ),
        migrations.AddField(
            model_name='gift',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_claimed', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='giftapp.gift')),
                ('gifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('reveals', models.ManyToManyField(blank=True, related_name='gift_reveals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
