# Generated by Django 5.1.6 on 2025-08-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0003_remove_gift_claimed_by_remove_gift_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='gift_gifs'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_images'),
        ),
    ]
