# Generated by Django 5.1.6 on 2025-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0004_gift_gif_alter_gift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='expire_rate',
            field=models.PositiveIntegerField(default=1, help_text='Number of days before gift expires.'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='If the actual gift is shown or hidden.'),
        ),
    ]
