# Generated by Django 5.1.6 on 2025-08-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0005_gifttransaction_expire_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
