# Generated by Django 5.1.6 on 2025-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0006_gifttransaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If the actual gift is shown or hidden.'),
        ),
    ]
