# Generated by Django 5.1.6 on 2025-08-26 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0007_alter_gifttransaction_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
