# Generated by Django 5.1.6 on 2025-08-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0008_alter_gifttransaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=1, help_text='Number of days before gift drops.'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='is_fastest_finger',
            field=models.BooleanField(default=False, help_text='If the gift is won by fastest finger only.'),
        ),
    ]
