# Generated by Django 5.1.6 on 2025-08-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0009_gifttransaction_drop_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
