# Generated by Django 5.1.6 on 2025-08-27 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0010_alter_gifttransaction_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
