# Generated by Django 5.1.6 on 2025-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0011_alter_gifttransaction_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of days before gift drops.'),
        ),
    ]
