# Generated by Django 5.1.6 on 2025-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0012_alter_gifttransaction_drop_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before gift drops.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='expire_rate',
            field=models.PositiveIntegerField(default=1, help_text='Number of hours before gift expires.'),
        ),
    ]
