# Generated by Django 5.1.6 on 2025-08-27 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0013_alter_gifttransaction_drop_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='claim_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
