# Generated by Django 5.1.6 on 2025-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0014_gifttransaction_claim_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='claim_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
