# Generated by Django 5.1.6 on 2025-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0015_alter_gifttransaction_claim_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='expire_rate',
            field=models.PositiveIntegerField(default=1, help_text='Number of hours before gift expires. Must be greater than drop rate.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of gift to buy.'),
        ),
    ]
