# Generated by Django 5.1.6 on 2025-08-30 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0016_user_keys_alter_gifttransaction_expire_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='paid_users',
            field=models.ManyToManyField(blank=True, related_name='paid_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
