# Generated by Django 5.1.6 on 2025-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0017_gifttransaction_cost_gifttransaction_paid_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to reveal the gift early. FFM gifts cannot have early reveal cost greater than 0.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before gift drops. Drop rates for non FFM gifts must be 0.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of this gift to buy.'),
        ),
    ]
