# Generated by Django 5.1.6 on 2025-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0018_alter_gifttransaction_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='won_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before the gift drops (0 - 23). Drop rates for non FFM gifts must be 0.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='expire_rate',
            field=models.PositiveIntegerField(default=1, help_text='Number of hours before the gift expires (1 - 24). Must be greater than drop rate.'),
        ),
    ]
