# Generated by Django 5.1.6 on 2025-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0019_user_won_coins_alter_gifttransaction_drop_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of coins paid to reveal the gift early. FFM gifts cannot have early reveal cost greater than 0.', null=True),
        ),
    ]
