# Generated by Django 5.1.6 on 2025-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0020_alter_gifttransaction_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to reveal the gift early. FFM gifts cannot have early reveal cost greater than 0.'),
        ),
    ]
