# Generated by Django 5.1.6 on 2025-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0021_alter_gifttransaction_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to reveal the gift early. FF gifts cannot have early reveal cost greater than 0.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before the gift drops (0 - 23). Drop rates for non FF gifts must be 0.'),
        ),
    ]
