# Generated by Django 5.1.6 on 2025-09-03 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0022_user_deactivated_at_alter_gifttransaction_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifttransaction',
            name='claim_time',
        ),
        migrations.CreateModel(
            name='FastestFingerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('gift_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ff_claims', to='giftapp.gifttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gift_transaction', 'user')},
            },
        ),
    ]
