# Generated by Django 5.1.6 on 2025-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0023_remove_gifttransaction_claim_time_fastestfingerclaim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastestfingerclaim',
            options={'ordering': ['reaction_time_ms']},
        ),
        migrations.AddField(
            model_name='fastestfingerclaim',
            name='reaction_time_ms',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
