# Generated by Django 5.1.6 on 2025-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0024_alter_fastestfingerclaim_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastestfingerclaim',
            name='reaction_time_ms',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
