# Generated by Django 5.1.6 on 2025-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0025_alter_fastestfingerclaim_reaction_time_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastestfingerclaim',
            name='reaction_time_ms',
            field=models.FloatField(null=True),
        ),
    ]
