# Generated by Django 5.1.6 on 2025-09-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0026_alter_fastestfingerclaim_reaction_time_ms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fastestfingerclaim',
            unique_together=set(),
        ),
    ]
