# Generated by Django 5.1.6 on 2025-09-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0027_alter_fastestfingerclaim_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastestfingerclaim',
            options={},
        ),
    ]
