# Generated by Django 5.1.6 on 2025-09-03 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0028_alter_fastestfingerclaim_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='drop_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
