# Generated by Django 5.1.6 on 2025-09-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0029_gifttransaction_drop_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to claim FF gifts if paid.'),
        ),
    ]
