# Generated by Django 5.1.6 on 2025-09-12 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0030_gifttransaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before the gift drops (0 - 23).'),
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=256)),
                ('amount', models.PositiveIntegerField(help_text='Number of coins user purchased.')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
