# Generated by Django 5.1.6 on 2025-09-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0031_alter_gifttransaction_drop_rate_coinpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinpurchase',
            old_name='recipient',
            new_name='user',
        ),
    ]
