# Generated by Django 5.1.6 on 2025-09-12 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0032_rename_recipient_coinpurchase_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinpurchase',
            old_name='purchase_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
