# Generated by Django 5.1.6 on 2025-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0033_rename_purchase_id_coinpurchase_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_email_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
