# Generated by Django 5.1.6 on 2025-09-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0034_user_change_email_code_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpurchase',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
