# Generated by Django 5.1.6 on 2025-10-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0035_coinpurchase_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifttransaction',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='gifttransaction',
            name='fee',
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='claim_fee',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to claim the gift if dropped.'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='early_claim_fee',
            field=models.PositiveIntegerField(default=0, help_text='Number of coins paid to claim the gift early if not dropped. FF gifts cannot have early claim fee greater than 0.'),
        ),
    ]
