# Generated by Django 5.1.6 on 2025-11-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0036_remove_gifttransaction_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='claim_fee',
            field=models.PositiveIntegerField(default=0, help_text='Number of keys paid to claim the gift if dropped.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='drop_rate',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours before the gift drops (0 - 23). Drop rates for FF gifts must be 0.'),
        ),
        migrations.AlterField(
            model_name='gifttransaction',
            name='early_claim_fee',
            field=models.PositiveIntegerField(default=0, help_text='Number of keys paid to claim the gift early if not dropped. FF gifts cannot have early claim fee greater than 0.'),
        ),
        migrations.DeleteModel(
            name='FastestFingerClaim',
        ),
    ]
