# Generated by Django 5.1.6 on 2025-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0037_alter_gifttransaction_claim_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransaction',
            name='claim_fee',
            field=models.PositiveIntegerField(default=1, help_text='Number of keys paid to claim the gift if dropped.'),
        ),
    ]
